on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.0.0
      with:
        server: ${{ secrets.server_ip }}
        username: sftpuser
        password: ${{ secrets.password }}
        server-dir: /var/www/virtualdream.live/deploy/
